apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tdh-biz-doctor-apmv2
  description: Consultation API service
spec:
  type: service
  lifecycle: production
  owner: user:default/p-bank
  providesApis:
    - consultation-rs-api
  consumesApis:
    - walrus-apm-booking-gate

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tdh-biz-doctor-apmv2
  description: Consultation service API
spec:
  type: openapi
  lifecycle: production
  owner: user:default/p-bank
  definition:
    $text: ./specs/provides/consultation-rs.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: walrus-apm-booking-gate
  description: Walrus APM booking gate API
spec:
  type: openapi
  lifecycle: production
  owner: user:default/p-bank
  definition:
    $text: ./specs/depends-on/walrus-apm-booking-gate.openapi.yaml
