apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: consultation-rs
  description: Consultation service API
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: ./specs/provides/consultation-rs.yaml
