#!/bin/sh

SQL_OUT_FILE=$(mktemp)

cat <<EOF >"$SQL_OUT_FILE"
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA v2 TO $DB_SERVICE_RW_USER;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA v2 to $DB_SERVICE_RW_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ADMIN_USER IN SCHEMA v2 GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO $DB_SERVICE_RW_USER;
  ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ADMIN_USER IN SCHEMA v2 GRANT USAGE, SELECT ON SEQUENCES to $DB_SERVICE_RW_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ADMIN_USER IN SCHEMA v2 GRANT SELECT ON TABLES TO $DB_SERVICE_RO_USER;
  ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ADMIN_USER IN SCHEMA v2 GRANT USAGE, SELECT ON SEQUENCES to $DB_SERVICE_RO_USER;

  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA v2 TO $DB_SERVICE_RW_USER;
  GRANT SELECT ON ALL TABLES IN SCHEMA v2 TO $DB_SERVICE_RO_USER;

  GRANT CONNECT ON DATABASE $DB_NAME TO $DB_ADMIN_USER;
  GRANT CONNECT ON DATABASE $DB_NAME TO $DB_SERVICE_RW_USER;
  GRANT CONNECT ON DATABASE $DB_NAME TO $DB_SERVICE_RO_USER;
  GRANT USAGE ON SCHEMA v2 TO $DB_ADMIN_USER;
  GRANT USAGE ON SCHEMA v2 TO $DB_SERVICE_RW_USER;
  GRANT USAGE ON SCHEMA v2 TO $DB_SERVICE_RO_USER;
  GRANT CREATE ON DATABASE $DB_NAME TO $DB_ADMIN_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA v2 TO $DB_SERVICE_RW_USER;
  GRANT SELECT ON ALL TABLES IN SCHEMA v2 TO $DB_SERVICE_RO_USER;
EOF

run-pgsql-script.sh ${DB_NAME} ${DB_ADMIN_USER} "${DB_ADMIN_USER_PASS}" $SQL_OUT_FILE
rm "$SQL_OUT_FILE"
