#[derive(utoipa::OpenApi)]
#[openapi(
    info(
        title = "Consultation API",
        version = "0.1.0",
        description = "API for managing consultations and appointments",
        license(name = ""),
    ),
    paths(
        crate::appointment::get_detail::handler::get_appointment_detail,
        crate::appointment::consultation_summary::handler::get_consultation_summary,
        crate::appointment::list::handler::list_appointments,
        crate::appointment::hold::handler::public_booking,
        crate::appointment::hold::handler::internal_booking,
        crate::appointment::hold::handler::public_booking_state,
        crate::appointment::hold::handler::internal_booking_state,
        crate::appointment::hold::handler::internal_cancel_booking,
        crate::doctor_timeslot::get_timeslot::handler::get_available_timeslots,
        crate::doctor_timeslot::get_timeslot::handler::get_available_doctors,
        crate::doctor_timeslot::get_timeslot::handler::get_scheduled_availability,
        crate::doctor_timeslot::reserved_timeslot::handler::get_reserved_timeslots,
        crate::consultation::session_info::handler::get_session_info,
        crate::consultation::end_session::handler::end_session,
        crate::consultation::patient_verification::handler::match_handle,
        crate::consultation::patient_verification::handler::miss_match_handle,
        crate::consultation::facial_upload::handler::facial_upload,
        crate::consultation_config::handler::get_schedule_config,
        crate::consultation_config::handler::update_schedule_config,
        crate::consultation_config::handler::get_availability,
        crate::consultation_config::handler::update_schedule_availability,
        crate::consultation_config::handler::update_instant_availability,
        crate::internal::handlers::create_confirmed_appointment,
        crate::internal::handlers::create_appointment,
        crate::summarization::handler::add_summary_note,
    ),
    components(
        schemas(
            crate::protocol::follow_up::FollowUp,
            crate::protocol::follow_up::FollowUpAppointment,
            crate::protocol::follow_up::VisitType,
            crate::common::tdh_protocol::internal::CreateAppointmentRequest,
            crate::common::tdh_protocol::internal::CreateAppointmentResult,
            crate::appointment::get_detail::model::AppointmentDetail,
            crate::appointment::get_detail::model::GetAppointmentDetailResponse,
            crate::appointment::get_detail::model::PartialUserIdentity,
            crate::appointment::get_detail::model::PrescreenInfo,
            crate::appointment::consultation_summary::model::ConsultationSummaryResponse,
            crate::appointment::consultation_summary::model::ConsultationSummary,
            crate::appointment::consultation_summary::model::ConsultationSummaryNote,
            crate::appointment::consultation_summary::model::DoctorRef,
            crate::appointment::list::model::ListAppointmentsResponse,
            crate::appointment::list::model::AppointmentList,
            crate::appointment::list::model::AppointmentListItem,
            crate::appointment::list::model::AppointmentDoctor,
            crate::doctor_timeslot::reserved_timeslot::model::ReserveTimeSlot,
            crate::doctor_timeslot::reserved_timeslot::model::ReservedTimeslotsResponse,
            crate::appointment::types::AppointmentTime,
            crate::appointment::hold::model::PublicBookingRequest,
            crate::appointment::hold::model::InternalBookingRequest,
            crate::appointment::hold::model::BookingResponse,
            crate::appointment::hold::model::BookingResponseStatus,
            crate::appointment::hold::model::BookingStateResponse,
            crate::appointment::hold::model::BookingCancelResponse,
            crate::appointment::hold::model::BookingLifecycle,
            crate::doctor_timeslot::get_timeslot::model::AvailableDoctor,
            crate::doctor_timeslot::get_timeslot::model::AvailableDoctorsResponse,
            crate::doctor_timeslot::get_timeslot::model::AvailableTimeslot,
            crate::doctor_timeslot::get_timeslot::model::AvailableTimeslotResponse,
            crate::protocol::summary_note::DrugAllergy,
            crate::protocol::summary_note::DurationUnit,
            crate::protocol::summary_note::Icd10,
            crate::repo::enums::AppointmentStatusEnum,
            crate::repo::enums::BookingTypeEnum,
            crate::repo::enums::ConsultationChannelEnum,
            crate::consultation_config::model::TimePeriod,
            crate::consultation_config::model::DateWithTimePeriods,
            crate::consultation_config::model::ScheduleAvailableConfig,
            crate::consultation_config::model::UpdateScheduleConfigResponse,
            crate::consultation_config::model::UpdateAvailabilityRequest,
            crate::consultation_config::model::AvailabilityResponse,
            crate::consultation_config::model::SuccessResponse,
            crate::consultation_config::model::DoctorIdentity,
            crate::consultation_config::model::EventSource,
            crate::consultation::end_session::handler::EndSessionRequest,
            crate::consultation::end_session::handler::EndSessionTerminateCode,
        )
    ),
    tags(
        (name = "appointment", description = "Appointment management API"),
        (name = "booking", description = "Booking route adapter vocabulary for canonical Appointment Hold API"),
        (name = "doctor-timeslot", description = "Doctor timeslot API"),
        (name = "consultation", description = "Consultation session management API"),
        (name = "consultation-config", description = "Doctor consultation configuration API"),
        (name = "internal", description = "Internal API for service-to-service communication"),
        (name = "summarization", description = "Doctor summary note management API"),
    )
)]
pub struct ApiDoc;

pub mod schemas;
